---
bibliography: LargeScale_MS_biblio.bib
csl: journal-of-applied-ecology.csl
output:
  word_document:
    fig_caption: yes
    reference_docx: DefaultMSstyle.docx
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE, results='hide'}
library(pander, quietly=T)
library(knitr, quietly=T)
library(Hmisc, quietly=T, warn.conflicts=F)
library(lme4, quietly=T)
library(MuMIn, quietly=T, warn.conflicts=F)
suppressMessages(library(arm))
suppressMessages(library(plyr, quietly=T, warn.conflicts=F))

opts_chunk$set(dpi = 200)

pasteLabel <- function(preText, inObj, objName, insLink=FALSE){
  objNum <- inObj[objName]
  useText <- paste(preText, objNum, sep=" ")
  if (insLink){
    useText <- paste("[", useText, "](#", objName, ")", sep="")
}
useText
}
 
# this increments the counter, and gives a name to the number so we can reference it later
incCount <- function(inObj, useName){
  nObj <- length(inObj)
  useNum <- max(inObj) + 1
  inObj <- c(inObj, useNum)
  names(inObj)[nObj+1] <- useName
  inObj
}
figCount <- c("_"=0)
tableCount <- c("_"=0)
 
tableCat <- function(inFrame){
    outText <- paste(names(inFrame), collapse=" | ")
    outText <- c(outText, paste(rep("---", ncol(inFrame)), collapse=" | "))
    invisible(apply(inFrame, 1, function(inRow){
    outText <<- c(outText, paste(inRow, collapse=" | "))
    }))
  return(outText)
} 

### Load data

load('DataResults/bats_nona.Rdata')
load('DataResults/mod_habz1.Rdata')
load('DataResults/TAB_all_hab.Rdata')
load('DataResults/m2.Rdata')
load('DataResults/m2_null.Rdata')
load('DataResults/m2z_set1.Rdata')
load('DataResults/TAB_mainmod_subset.Rdata')
load('DataResults/m2z_av.Rdata')
load('DataResults/m2z_set1_mods.Rdata')
load('DataResults/TAB_main_model_intputs_summary.Rdata')
load('DataResults/TAB_coefs_av.Rdata')
load('DataResults/TAB_imp.Rdata')
load('DataResults/FIG_predictions1.Rdata')
obsdat <- subset(bats_nona, select=c('OCC_PIPS','fSECTION','TURB'))
wtd_mn_single <- apply(mn_single, 2, function(x) wtd.mean(x, weights=subset(m2z_set1,delta<4)$weight))
wtd_lo_single <- apply(lo_single, 2, function(x) wtd.mean(x, weights=subset(m2z_set1,delta<4)$weight))
wtd_hi_single <- apply(hi_single, 2, function(x) wtd.mean(x, weights=subset(m2z_set1,delta<4)$weight))
wtd_mn_multiple <- apply(mn_multiple, 2, function(x) wtd.mean(x, weights=subset(m2z_set1,delta<4)$weight))
wtd_lo_multiple <- apply(lo_multiple, 2, function(x) wtd.mean(x, weights=subset(m2z_set1,delta<4)$weight))
wtd_hi_multiple <- apply(hi_multiple, 2, function(x) wtd.mean(x, weights=subset(m2z_set1,delta<4)$weight))

### Table index:
tableCount <- incCount(tableCount, "TAB_main_model_inputs_summary")   # Table 1
  write.csv(TAB_main_model_inputs_summary, 'Table 1.csv')
tableCount <- incCount(tableCount, "TAB_mainmod_subset")              # Table 2
  write.csv(TAB_mainmod_subset, 'Table 2.csv', row.names=F)
tableCount <- incCount(tableCount, "TAB_coefs_av")                    # Table 3
  write.csv(TAB_coefs_av, 'Table 3.csv')

### Figure code:
figCount <- incCount(figCount, "transect diagram")
tiff('FIG2.tiff',width=800,height=600,compression='none')
FIG2 <- function() {
  bars <- barplot(tapply(obsdat$OCC_PIPS, list(obsdat$TURB, obsdat$fSECTION), mean),beside=T,ylim=c(0,0.5), 
                  col=c('white','grey'), xaxt='n', xlab='Distance band', ylab='Probability of a Pipistrelle bat pass / ha')
  axis(1, at=apply(bars,2,mean), labels=c('0-100m','100-200m','200-300m','300-400m','400-500m'))
  for(i in 1:length(bars[1,])) {
      arrows(bars[1,][i], wtd_lo_single[i] ,bars[1,][i], wtd_hi_single[i], angle=90, code=3, length=0.1)
      arrows(bars[2,][i], wtd_lo_multiple[i],bars[2,][i], wtd_hi_multiple[i], angle=90, code=3, length=0.1)    
  }
  points(bars[1,], wtd_mn_single, cex=1.5, pch=21, col='black', bg='lightgrey')
  points(bars[2,], wtd_mn_multiple, cex=1.5, pch=21, col='black', bg='black')
}; FIG2(); dev.off()
figCount <- incCount(figCount, "model_predictions1")

### Calculate variables for text:
source('Main_text_variables.R')


```

# No evidence for cumulative effects of small wind turbines on bat activity
*Jeroen Minderman^1$^, Mairi H. Gillis^2^, Helen F. Daly^3^ & Kirsty J. Park^1^*    


1. Biological & Environmental Sciences, University of Stirling, Stirling, FK9 4LA, United Kingdom. 
2. 228 Galashiels Road, Stow, Galashiels, Selkirkshire, TD1 2RA, mgillis4a7i@gmail.com 
3. 20/11 Duff Street, Dalry, Edinburgh, Midlothian, EH11 2HG, hfdaly@outlook.com 
 
^$^***Corresponding author***. Current address: School of Biology, University of St Andrews, St Andrews, Fife, KY16 9ST, UK. Email: jm340@st-andrews.ac.uk.  

**Running title**: Cumulative effects of small wind turbines on bats

**Word counts**
*Summary*:
*Main text*:
*Acknowledgements*:
*References*:
*Table & Figure legends*:
*No. of tables and figures*:
*No. of references*:

# Summary

1. While the effects of large wind farms on wildlife (particularly birds and bats) are generally well-studied, similar effects of small wind turbines (SWTs, in the UK usually up to 25m in hub height) remain relatively unknown. This is problematic, because rapid development and increasing accessibility of SWT technology have led to rapid growth of the number of SWTs installed worldwide.    

2. Although recent studies showed that bat activity is negatively affected by the immediate proximity of single operating SWTs, the potential for wider landscape-scale effects of multiple SWTs installed in clusters remains unstudied. By contrast, such cumulative effects are commonly considered in impact assessments of large wind farms.    

3. We measured variation in bat activity at a sample of `r n_sites` SWT sites in the UK (free-standing SWTs between 6 and 25m in hub height), in order to test whether (1) accounting for variation in habitat, bat activity is generally lower in closer proximity of installed SWTs (e.g. 0-100m, compared to 100-200m, 200-300m, etc.), and (2) whether this effect is stronger in sites with multiple SWTs compared to sites with single turbines.    

4. We focused our analysis on *Pipistrellus* bats (*Pipistrellus pipistrellus* Schreber and *P. pygmaeus* Leach) because more than 98% of our recorded activity was from this genus. We show that although observed *Pipistrellus* activity was up to 10% lower within 100m of multiple turbine sites compared to activity at 100-200m, after accounting for confounding effects of habitat and environmental conditions, there is no effect of turbine proximity, irrespective of the number of turbines installed. 

5. *Synthesis and applications*. In our sample there is no evidence of cumulative effects of SWTs on the activity of *Pipistrellus* bats on a landscape scale (i.e. over >100m distances). Our previous studies did show that single SWTs may adversely affect bat activity on smaller spatial scales (within 25m), so the combination of these findings suggest that any adverse effects of SWTs may be relatively localised, even if more than one SWT is present. These findings are of vital importance to planners and decisions makers seeking to maximise renewable energy generation whilst minimising the risk of adverse effects on bats.

**Key words**: microturbines, domestic turbines, renewables, renewable energy, conservation, planning, wildlife impact
  

# Introduction

Understanding and predicting how wildlife is affected by disturbance or habitat loss is becoming increasingly important as anthropogenic pressures on the natural world continue to grow [@tuomainen_behavioural_2011]. This is particularly pertinent where incremental changes or disturbances could combine to produce cumulative effects. For example, whilst the rapid growth of the wind energy sector worldwide provides a vital contribution to sustainable energy production, a growing number of studies show that wind farms can have adverse effects on wildlife [@kuvlesky_wind_2007]. Although the recognition of the potential importance of cumulative effects (defined as "*the additional changes caused by a proposed development in conjunction with other similar developments or as the combined effect of a set of developments, taken together*", SNH [-@snh_assessing_2012]) is relatively recent and its quantification is in its infancy [@masden_cumulative_2010], both direct (collision mortality of birds and bats, e.g. Drewitt & Langston [-@drewitt_assessing_2006], Rydell *et al*. [-@rydell_bat_2010]) and indirect effects (disturbance or displacement, e.g. Larsen & Guillemette [-@larsen_effects_2007], Pearce-Higgins *et al*. [-@pearce-higgins_distribution_2009]) of individual turbines or wind farms have been widely studied. 

By contrast, similar effects of small wind turbines (SWTs, also referred to as micro-turbines or domestic turbines) on wildlife remain relatively unknown. These turbines are not only much smaller in size (in the UK, typical units are between 6 and 25m hub height) than those in wind farms, they are also commonly installed in a much wider range of habitats. Thus, their impacts on wildlife are likely to be different to that of large turbines, but up until recently this had not been quantified systematically. Our previous work found evidence for adverse effects of SWTs on bat activity [@minderman_experimental_2012, Tatchley et al. submitted] as well as direct mortality [@minderman_estimates_2014]. These previous studies focused on a relatively limited spatial scale (e.g. within 25m of installed SWTs) and on single SWTs only. As a result, it is unclear whether any such adverse effects of SWTs on wildlife could be cumulative, i.e. whether the combined effects of multiple SWT installations could have greater adverse effects on wildlife.

This lack of understanding of the potential cumulative effects of SWTs is particularly important for two reasons. First, the number of SWTs installed is growing rapidly, both in the UK and worldwide and this growth is set to continue [@wwea_2013_2013; @renewableuk_small_2014]. Secondly, the number of SWTs installed in groups is growing rapidly, with installations of 2-4 turbines now relatively common in the UK. Indeed, some installers specifically promote the installation of multiple SWTs to maximise yield and potential government grants or payback schemes. As a result, where SWT installation requires planning permission [@park_integrating_2013], decision makers are increasingly asked to decide whether multiple-turbine installations would have greater effects on wildlife, or if limiting the number of SWTs to be installed would be an effective mitigation option. Currently, the evidence base for such decisions for SWTs specifically is entirely lacking.

Here, we aim to address this knowledge gap by quantifying and analysing the potential cumulative effect of SWTs on bat activity on a wider landscape scale (up to 500m from installed turbines). Specifically, using data collected at `r n_sites` SWT sites throughout the UK we test the following predictions:

1. Bat activity is systematically lower in closer proximity (e.g. 0-100m from SWTs compared to 100-200m, 200-300m, etc.) of operating SWTs, controlling for the effects of habitat and environmental conditions.    

2. The effect of SWT proximity on bat activity as tested in Prediction 1 is stronger in sites with multiple (2-4) SWTs installed compared to single SWT sites. Support for this prediction would indicate evidence of cumulative effects of SWTs.    

# Materials and methods

## Sites

Data were collected at `r n_sites` SWT sites in central and eastern Scotland. Sites were selected from an existing database of owners [@minderman_experimental_2012; @park_integrating_2013] based on how representative they were of common UK SWT installation settings in terms of habitat, turbine models and size. All turbines studied here were free-standing and between 6 and 25m (mean 16m) in hub height, and all were in rural settings but specific habitat in the surrounding area varied (see [Habitat data and variable selection]). The number of SWTs installed in each site varied between `r n_turb_min` and `r n_turb_max` (median `r n_turb_mn`). SWTs installed in individual sites were the same size and specification with the exception of one site. More than two SWTs were installed in only `r site_more_2_turb` sites in our sample. We therefore limited the analyses presented here to a comparison of single and multiple turbine sites.

## Bat data and transects

Bat activity data were collected between `r date_min_13` and `r date_max_13` and `r date_min_14` and `r date_max_14`. The time of data collection varied but started 30 minutes after sunset at the earliest and finished well before sunrise in all cases.  

Bat activity was measured along transects by 1-2 observers walking the length of each transect at a slow (approximately 2.5km h^-1^) and constant pace, using EchoMeter EM3+ bat detectors (WildLife Acoustics, Mass., USA). 
A target of four transects was planned for all sites, running out from the turbine (or the central point between turbines in the case of multiple turbine sites) in four cardinal directions. However, because of physical constraints (e.g. walls, impassable fences or ditches, houses or buildings) the actual number of transects per site as well as their length varied (`r min_trscts`-`r max_trscts`, mean `r round(mean_trscts,1)` per site, length: 300-500m). All transects were placed so that (1) the combination of all transects within each site covered all major habitats present, and (2) overall distance separating each transect was maximised. Transects were divided into 100m sections running out from the turbine centre point, giving up to five distance bands running away from the turbine. See `r pasteLabel('Figure', figCount, 'transect diagram')` for an example transect and transect section layout.

One measure of ground level wind speed was taken at the end of each section (i.e. in each distance band) on each survey visit using handheld anemometers, and minimum daily temperature measures for each survey visit were obtained from the UK MIDAS weather station data at Grangemouth (N 56° 1' 5.15, W 3° 43' 5.88) [@uk_meteorological_office_midas_2006].

## Habitat data and variable selection

To account for expected confounding effects of habitat variation on bat activity along the transects, we collated measurements of habitat availability per transect section. To do this, we placed 50m buffers around digital maps of each transect route, resulting in approximately 100m x 100m transect sections. The exact area of each section varied because of non-linear transect sections, but this was accounted for in the analysis, see [Statistical analysis] and `r pasteLabel('Figure', figCount, 'transect diagram')`. All habitat variables were quantified in each transect section using  1:1250 UK Ordnance Survey MasterMap Topography digital maps, using QGIS v. 1.8 [@quantum_gis_development_team_quantum_2014].
We focused on two key measures of habitat variability in each transect section:

1. **Edge density** (m m^-2^) represented the density of "edge" habitat in each transect section, and was calculated as the total length of all linear habitat features ("line" data in the OS Topography Layer) divided by the area of the transect section. Thus, this is a description of the density of e.g. building-, woodland and water edges, hedgerows, roads and tracks, roadsides, field boundaries.   

2. The **proportion of woodland** in each transect section was the sum of all tree coverage (m^2^) (coniferous, non-coniferous and unclassified trees) in the OS Topography polygon data divided by the transect section area.  

These two variables were selected on the basis of a preliminary analysis of the effect of a full set of `r n_hab_var` habitat variables on bat activity. This was done to avoid both overparameterisation of the main statistical models presented here, as well as the inclusion of highly collinear habitat metrics. Full details of this preliminary analysis and the selection of the two focal variables are given in Appendix 1.

## Data analysis and statistics

### Bat activity: probability of a pass per hectare surveyed

Bat activity was initially quantified as the number of bat 'passes' (defined as a sequence of at least two echolocation calls separated by less than a second) per transect section. However, we chose to analyse our data as bat activity presence or absence per transect section, per survey visit, because the distribution of observed counts was highly skewed (many zeros and excessive variation) so that count-based statistical models did not provide any reasonable fit. In addition, because the area covered by each transect section varied slightly (see [Bat data and transects]), we here model the probability of detecting bat activity per section and hectares covered.

### Statistical analysis

We used generalised linear mixed effects models (GLMMs) [@gelman_data_2007] and an Information-Theoretic model selection (IT) approach [@burnham_model_1998] to analyse our data. 

#### Model structure

We modelled the probability of a bat pass per unit area on a given survey visit as the response variable with a GLMM with binomial errors and a complementary log-log link function. This link function allowed us to include transect section area as an offset in the model (thus accounting for slight variation in the size of each transect section, see [Bat data and transects] and `r pasteLabel('Figure', figCount, 'transect diagram')`). To account for the non-independence of repeated measurements from the same site and transect sections, all models included transect nested within site as a random effect. 
To test our two predictions (see [Introduction]), we included two focal fixed factors; (1) transect section (distance bands; 0-100m, 100-200m, 200-300m, 300-400m and 400-500m from the SWTs) and (2) turbine number (single or multiple SWTs), as well as the statistical interaction between the two. In addition to these focal factors we included the two selected (see [Habitat data and variable selection]) habitat variables (edge density and proportion of woodland) as continuous covariates. Moreover, because bat activity is known to vary with weather conditions (particularly temperature and wind speed) across the season and through the night, we also included covariates for the minimum temperature over 24h (C), wind speed (m s^-1^), Julian day number, time to midnight (minutes) and time to midnight^2^ (to account for potential non-linear effects of the latter). We used time to midnight instead of time since sunset to account for variation in bat activity through the night to avoid colinearity issues with date.
Thus, accounting for any confounding effects of habitat and environmental conditions, a transect section effect would indicate a systematic difference in bat activity as a function of distance from SWTs (Prediction 1), and an interaction between this and turbine number would indicate that the strength of this effect depends on the number of SWTs installed (Prediction 2). To avoid overparameterisation of the model, interactions between confounding effects were not considered.
All inputs were standardised (centred to 0 and scaled to 2 SD) following Gelman [-@gelman_scaling_2008] to improve performance of parameter estimation and allow for direct interpretation of relative effect strength, but we calculate and present model predictions on the response scale. Summary statistics of unstandardised model inputs are given in `r pasteLabel('Table', tableCount, 'TAB_main_model_inputs_summary')`.  

#### Model selection, averaging and predictions

The full model set was constrained to (1) only include the time to midnight^2^ term when its linear term was also included, (2) include all random effects in all models, and (3) use the same link function and distribution for all models, yielding a total of N = `r n_mods_full_set` models. Model fit was assessed using the adjusted Akaike Information Criterion (AICc) and we took the top models within 4 AICc points of the 'top' model as our candidate set. To account for model selection uncertainty within the candidate set, we interpret the averaged parameter estimates and their standard errors calculated using the 'zero method' [@burnham_model_1998]. Prediction intervals were calculated as the 95% quantiles (weighted by model weight) of predictions from N = 1000 simulated draws from the estimated parameter distributions for each of the models in the candidate set [@gelman_data_2007]. For each model in the candidate set we also present the marginal and conditional R^2^ [@nakagawa_general_2013].

We used `r R.Version()$version.string` [@r_development_core_team_r:_2015] for all statistical analyses. GLMMs were fitted using package *lme4* v. `r lme4.v` [@bates_lme4:_2014]. Model selection and averaging was performed using package *MuMIn* v. `r MuMIn.v` [@barton_mumin:_2015], and standardisation of model inputs and parameter simulation used package *arm* v. `r arm.v` [@gelman_arm:_2014].

# Results

Over the two years of the study, we collected bat activity data in N = `r n_total` transect sections, during `r n_surveys` survey visits. Most sites (N = `r n_surveys_p_site_min2`) were surveyed on at least two occasions (2-6 surveys), but four sites were only visited once. Within this sample, N = `r n_turb_single` were single-turbine sites, and N = `r n_turb_multiple` were multiple-turbine sites (2-4 turbines). In total, we recorded N = `r n_pass` bat passes, of which `r round(n_pass_pip_prop,1)`% (N = `r n_pass_pip`) were *Pipistrellus* sp. (*Pipistrellus pipistrellus*, N = `r n_pass_compip` [`r round(n_pass_compip_prop,1)`%] or *P. pygmaeus*, N = `r n_pass_soppip` [`r round(n_pass_soppip_prop,1)`%]) bats (`r round(n_pass_unkpip_prop,1)`% of passes could only be determined to genus). Thus, here we only present analyses of *Pipistrellus* bat activity combined. Overall, *Pipistrellus* bat activity was detected on `r n_obs_with_pip` section surveys (observed average probability of a *Pipistrellus* pass = `r prop_obs_with_pip`).

The candidate set ($\Delta$AICc<4) of GLMMs for the probability of a bat pass per hectare contained `r nrow(TAB_mainmod_subset)-1` models. The top model retained 7 out of the 10 predictors in the full model, including distance band but neither the number of turbines nor an interaction between distance band and number of turbines. This model was $w_1/w_2$ = `r round(TAB_mainmod_subset[1,'weight'],3)`/`r round(TAB_mainmod_subset[2,'weight'],3)` = `r round(TAB_mainmod_subset[1,'weight']/TAB_mainmod_subset[2,'weight'],3)` (evidence ratio) times more strongly supported than second-best model, and $w_1/w_10$ = `r round(TAB_mainmod_subset[1,'weight'],3)`/`r round(TAB_mainmod_subset[10,'weight'],3)` = `r round(TAB_mainmod_subset[1,'weight']/TAB_mainmod_subset[10,'weight'],3)` times better supported than the saturated model (ranked 10^th^). The null model was ranked 446^th^ and had no support ($w_446$ < 0.001) (**`r pasteLabel('Table', tableCount, 'TAB_mainmod_subset')`**).

Although it was retained in the top model, four out of ten models in the candidate set did not retain an effect of distance band (predictor weight $w$ = `r round(sum(TAB_mainmod_subset$weight[which(TAB_mainmod_subset[,'fSECTION']=='+')]),2)`). The relative importance of both the number of turbines and its interaction with distance band was even lower ($w$ = `r sum(TAB_mainmod_subset$weight[which(!is.na(TAB_mainmod_subset[,'c.TURB']))])` and $w$ = `r round(sum(TAB_mainmod_subset$weight[which(!is.na(TAB_mainmod_subset[,'c.TURB.fSECTION']))]),2)`, retained in 5 and 2 models in the candidate set respectively). With the exception of minimum temperature ($w$ = `r round(sum(TAB_mainmod_subset$weight[which(!is.na(TAB_mainmod_subset[,'z.MINTEMP']))]),2)`) all other predictors were retained in all models in the candidate set (`r pasteLabel('Table', tableCount, 'TAB_coefs_av')`).

Thus, although at multiple turbine sites the observed probability of a *Pipistrellus* bat pass appeared to be lower in the closest (0-100m) distance band compared to the 100-200m distance band, this difference was relatively small (`r round(tapply(obsdat$OCC_PIPS, list(obsdat$TURB, obsdat$fSECTION), mean)['multiple',1],2)` vs. `r round(tapply(obsdat$OCC_PIPS, list(obsdat$TURB, obsdat$fSECTION), mean)['multiple',2],2)`) (`r pasteLabel('Figure', figCount, 'model_predictions1')`, dark bars, and `r pasteLabel('Table', tableCount, 'TAB_coefs_av')`). Moreover, this effect is no longer apparent when considering model predictions that account for the effects of habitat- and environmental conditions. For example, in multiple turbine sites, predicted bat activity ranged from `r round(wtd_lo_multiple[1],2)` to `r round(wtd_hi_multiple[1],2)` in the nearest distance band (0-100m), and from `r round(wtd_lo_multiple[2],2)` to `r round(wtd_hi_multiple[2],2)` in the 100-200m distance band. Similar overlapping prediction intervals apply for both single turbine sites as well as the further distance bands (`r pasteLabel('Figure', figCount, 'model_predictions1')`, points and error bars).

# Discussion

We show that, when accounting for confounding effects of habitat and environmental conditions, *Pipistrellus* sp. activity is not systematically lower within 100m of SWTs compared to at longer distances (100-200m, 200-300m, 300-400m and 400-500m), irrespective of the number of turbines (single or multiple) installed. On this basis, we conclude that there is no evidence for cumulative effects of SWTs on a landscape (i.e. >100m) scale. 

By contrast, we previously showed that bat activity can be systematically lower in the immediate vicinity (<25m) of operating SWTs [@minderman_experimental_2012], and indeed subsequent experimental studies of bat activity before- and after installation of SWTs near hedgerows confirmed such adverse effects on activity (Tatchley *et al*. submitted). Combined with the present finding of a lack of similar effects on a larger scale (i.e. within 100m), this suggests that such adverse effects are relatively localised. Although the mechanism causing such avoidance behaviour is unclear, experimental studies in a laboratory setting have shown that the return of echolocation pulses off spinning turbine blades may be erratic, potentially causing navigational problems for bats [@long_wind_2010]. Other experimental studies have shown that some species of bat may avoid foraging in noisy environments [@schaub_foraging_2008] but whether noise generated by turbines (including SWTs) has the same effect has not been tested. In either case, it would be reasonable to assume that the strength of such interference would dissipate relatively rapidly with distance, especially if it involves relatively high-frequency noise (which should attenuate more strongly over shorter distances)[@russ_british_2012], limiting the spatial scale of any adverse effect of the turbine.

This apparently relatively localised effect of SWTs may in turn also explain the lack of evidence for any cumulative effect (i.e. effects were not different between single- or multiple turbine sites). If avoidance behaviour only operates over relatively short (as per our previous findings, <25m) distances, it may be possible for bats to avoid individual turbines rather than whole "clusters" of turbines. Indeed, in our multiple turbine sites, turbines were sited `r min(dist_betw_turb$DIST)` - `r max(dist_betw_turb$DIST)` m apart with this distance being less than 23 m in only one case (mean `r round(mean(dist_betw_turb$DIST),1)`m). This suggests that in most cases bats would be able to avoid individual turbines without coming in very close proximity of another, limiting the possibility of any cumulative effects. Further detailed study of individual flight paths would be required to confirm whether this is the case, however. Moreover, it should be noted that although the possibility of cumulative effects is often raised for larger turbines and wind farms [@masden_cumulative_2010; @snh_assessing_2012], empirical studies that demonstrate such effects are rare and have tended to focus on birds rather than bats [@schaub_spatial_2012]. Although this may be due to the logistical difficulty of studying such large-scale effects, it is possible that cumulative effects themselves are rare, except in specific circumstances. 

There are a number of important caveats with our findings that should be considered. First of all, these findings and conclusions should not be generalised to species other than *Pipistrellus* sp. Although *Pipistrellus* bats are by far the commonest species in both our wider study area as well as in the specific habitats we studied [@middleton_introduction_2006], it is likely that the collection of sufficient data to draw species-specific conclusions would require targeted surveys. The need to collect data at a wide range of sites rather than in specific habitats (where less widespread species may be more abundant) prevented us from doing this here. However, larger turbines in wind farms are known to have different effects on different species [@cryan_causes_2009] and we therefore consider this to be a research priority for SWTs (Tatchley *et al.* submitted). Secondly, the limited number of sites with more than two turbines in our sample means that we cannot exclude the possibility that a larger number of turbines *would* cause cumulative effects; indeed modelling studies in birds [@schaub_spatial_2012] show that this may well be the case. Finally, the combination of recording bat activity over a relatively large scale (up to 500m from SWTs) along transects, and a distance-based approach to turbine effects, required that we analysed our data in distance bands. Our choice of relatively 'coarse' 100m distance bands may mean that we have missed more subtle cumulative effects of SWTs. However, our previous study had already established adverse effects on activity seem to approach zero over 25 m [@minderman_experimental_2012]. Moreover, accurately allocating bat passes to even more narrow distance bands is likely to introduce false precision. Thus, in our view data on behavioural responses to turbines on a finer scale would require alternative survey methods, e.g. flight path tracking [@holderied_echolocation_2003].

In conclusion, based on the data presented here it is unlikely that SWTs in the range of 6-25m hub height have adverse effects on bat activity on a landscape (>100 m) scale, or that such effects are cumulative (when considering 2-4 installed turbines). The SWT sector is expanding rapidly both in the UK and worldwide, and as a result planners and decision makers are increasingly faced with having to advise or decide on planned developments of multiple SWTs in clusters. To date, there was no data to inform such decisions, and the findings presented here are therefore vital and timely. While we reiterate our suggestion that individual SWTs should be sited away (>25m) from potentially valuable bat habitat [@minderman_experimental_2012], we additionally sugggest that cumulative effects on bats are less likely, at least for the sort of turbine size range considered here.

# Acknowledgements

We are extremely grateful to all site- and turbine owners who kindly allowed us access to their property for the survey work; this study would have been impossible without their help. Kathryn Hamilton made substantial contributions to the data collection in 2013, and Sofia Motta Pralon assisted with GIS data entry - thank you both. Many thanks to Cerian Tatchley, Paul Lintott, Nils Bunnefeld, Chris Pendlebury and Claudia Garratt for useful discussions. This study was funded by a University of Stirling Impact Fellowship to JM.

# Data archiving

Appropriate arrangements will be made upon acceptance of the paper.

# References {-}
